/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as UserRouteImport } from './routes/_user'
import { Route as UserIndexRouteImport } from './routes/_user/index'
import { Route as UserCartRouteImport } from './routes/_user/cart'
import { Route as UserLoginRouteImport } from './routes/_user/login'
import { Route as UserProductsRouteImport } from './routes/_user/products'
import { Route as UserProfileRouteImport } from './routes/_user/profile'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as AdminAdminCustomersRouteImport } from './routes/_admin/admin/customers'
import { Route as AdminAdminLoginRouteImport } from './routes/_admin/admin/login'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin/admin/orders'
import { Route as AdminAdminProductsRouteImport } from './routes/_admin/admin/products'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin/settings'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin/users'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const UserCartRoute = UserCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => UserRoute,
} as any)
const UserLoginRoute = UserLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UserRoute,
} as any)
const UserProductsRoute = UserProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCustomersRoute = AdminAdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminLoginRoute = AdminAdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProductsRoute = AdminAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof UserIndexRoute
  '/cart': typeof UserCartRoute
  '/login': typeof UserLoginRoute
  '/products': typeof UserProductsRoute
  '/profile': typeof UserProfileRoute
  '/admin/customers': typeof AdminAdminCustomersRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/': typeof AdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof UserIndexRoute
  '/cart': typeof UserCartRoute
  '/login': typeof UserLoginRoute
  '/products': typeof UserProductsRoute
  '/profile': typeof UserProfileRoute
  '/admin/customers': typeof AdminAdminCustomersRoute
  '/admin/login': typeof AdminAdminLoginRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin': typeof AdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_user': typeof UserRouteWithChildren
  '/_user/cart': typeof UserCartRoute
  '/_user/login': typeof UserLoginRoute
  '/_user/products': typeof UserProductsRoute
  '/_user/profile': typeof UserProfileRoute
  '/_user/': typeof UserIndexRoute
  '/_admin/admin/customers': typeof AdminAdminCustomersRoute
  '/_admin/admin/login': typeof AdminAdminLoginRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRoute
  '/_admin/admin/products': typeof AdminAdminProductsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/login'
    | '/products'
    | '/profile'
    | '/admin/customers'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/login'
    | '/products'
    | '/profile'
    | '/admin/customers'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/_admin'
    | '/_user'
    | '/_user/cart'
    | '/_user/login'
    | '/_user/products'
    | '/_user/profile'
    | '/_user/'
    | '/_admin/admin/customers'
    | '/_admin/admin/login'
    | '/_admin/admin/orders'
    | '/_admin/admin/products'
    | '/_admin/admin/settings'
    | '/_admin/admin/users'
    | '/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/': {
      id: '/_user/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/cart': {
      id: '/_user/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof UserCartRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/login': {
      id: '/_user/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UserLoginRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/products': {
      id: '/_user/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof UserProductsRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/profile': {
      id: '/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/customers': {
      id: '/_admin/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminAdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/login': {
      id: '/_admin/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminAdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/products': {
      id: '/_admin/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminCustomersRoute: typeof AdminAdminCustomersRoute
  AdminAdminLoginRoute: typeof AdminAdminLoginRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRoute
  AdminAdminProductsRoute: typeof AdminAdminProductsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminCustomersRoute: AdminAdminCustomersRoute,
  AdminAdminLoginRoute: AdminAdminLoginRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRoute,
  AdminAdminProductsRoute: AdminAdminProductsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface UserRouteChildren {
  UserCartRoute: typeof UserCartRoute
  UserLoginRoute: typeof UserLoginRoute
  UserProductsRoute: typeof UserProductsRoute
  UserProfileRoute: typeof UserProfileRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserCartRoute: UserCartRoute,
  UserLoginRoute: UserLoginRoute,
  UserProductsRoute: UserProductsRoute,
  UserProfileRoute: UserProfileRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
declare module '@tanstack/react-router' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
