# Android Release Keystore Configuration
# Keystore: android/app/upload-keystore.jks
# Alias: souliyapps

storePassword=Admin123
keyPassword=Admin123
keyAlias=souliyapps
storeFile=upload-keystore.jks
